// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZKBfQ_NFDTO5Z6eZ2YxOIAK_2KYHWOEo',
    appId: '1:602552143115:web:c49a1f9b19f0d53912e60e',
    messagingSenderId: '602552143115',
    projectId: 'local-rental',
    authDomain: 'local-rental.firebaseapp.com',
    storageBucket: 'local-rental.appspot.com',
    measurementId: 'G-NXP2LT5FWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUw1mCPQpLceyqnC_gG3bqFK4e6YWZnQ',
    appId: '1:602552143115:android:f5d95c8f2cf495a512e60e',
    messagingSenderId: '602552143115',
    projectId: 'local-rental',
    storageBucket: 'local-rental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4Ptu5z6t7ikqRPZSMbKm3FazEfZtG1k',
    appId: '1:602552143115:ios:4d279109d2604a7412e60e',
    messagingSenderId: '602552143115',
    projectId: 'local-rental',
    storageBucket: 'local-rental.appspot.com',
    iosBundleId: 'com.example.localRent',
  );
}
